spring.application.name=bytedesk-monitor
spring.thymeleaf.check-template-location=false
# bytedesk.monitor.version=3.0.0

# 默认使用对外演示配置，线上和本地可通过 SPRING_PROFILES_ACTIVE 覆盖
# spring.profiles.default=local
spring.profiles.default=open
# spring.profiles.default=prod
