spring.application.name=bytedesk-monitor
spring.thymeleaf.check-template-location=false
# bytedesk.monitor.version=3.0.0

# 默认使用对外演示配置，线上和本地可通过 SPRING_PROFILES_ACTIVE 覆盖
# spring.profiles.default=local
spring.profiles.default=open
# spring.profiles.default=prod

# ===============================
# Logging
# ===============================
logging.file.name=logs/bytedesk-monitor.log
logging.level.root=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30
